CREATE DATABASE IF NOT EXISTS test_9z_st;
USE test_9z_st;

DROP TABLE IF EXISTS  TICKER  ;
DROP TABLE IF EXISTS  SECURITY  ;

CREATE TABLE IF NOT EXISTS  SECURITY  (
   SECURITY_ID  INT(11) NOT NULL AUTO_INCREMENT,
   SYMBOL  VARCHAR(10) NOT NULL,
   NAME  VARCHAR(100) NULL,
   CREATED_DATE  DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY ( SECURITY_ID ),
  INDEX  SYMBOL  ( SYMBOL  ASC)
)
ENGINE = INNODB
DEFAULT CHARACTER SET = UTF8;


CREATE TABLE IF NOT EXISTS  TICKER  (
   TICKER_ID  INT(11) NOT NULL AUTO_INCREMENT,
   SYMBOL  VARCHAR(10) NOT NULL,
   PRICE  DECIMAL(11,6) NULL DEFAULT NULL,
   PRICE_DIFF  DECIMAL(11,6) NULL DEFAULT NULL,
   PERCENT_DIFF  DECIMAL(11,2)  AS (PRICE_DIFF*100/PRICE),
   PRICE_TS  DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY ( TICKER_ID ),
  CONSTRAINT  FK_TICKER_SYMBOL 
    FOREIGN KEY ( SYMBOL )
    REFERENCES  SECURITY  ( SYMBOL )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = INNODB
DEFAULT CHARACTER SET = UTF8;

INSERT INTO SECURITY(SYMBOL,NAME) 
VALUES
	('SPY', 'SPDR S&P 500 ETF Trust (ETF)'),
	('BABA', 'Alibaba Group Holding Ltd. ADR (NYS)'),
	('BTC-USD', 'BITCOIN IN USD'),
  ('^DJI','Dow Jones Industrial Average'),
	('PDD', 'Pinduoduo Inc.');

 
-- AS OF 2022.09.19 GMT+8 after market 
INSERT INTO TICKER(SYMBOL,PRICE,PRICE_DIFF)
VALUES
       
       ('BTC-USD', 18787.64, -1248.98),
       ('BABA', 86.50, 0.07),
       ('SPY', 387.45, 1.89 ),
       ('^DJI', 30822.42, -139.38),
       ('PDD', 65.56, -0.11);


SELECT * FROM SECURITY;
SELECT * FROM TICKER;
